package com.mkyong.web.controller;

import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.Scanner;

import com.mkyong.web.model.LineItem;
import com.mkyong.web.model.Transaction;

public class PrinterHelper {

	/**
	 * 
	 *     SAFIRE TEX - Tirupattur 
    Mobile : +91 99002 80517
***********************************

Bill No :  #_BILL_NO#
Customer Id : #_CUST_ID#

***********************************

#_LINE_ITEM_#

***********************************

Total :  #_SUB_TOTAL_#

Discount % : #_DISCOUNT_PERCENT_#

Discount Amount : #_DISCOUNT_AMOUNT_#

***********************************

Amount Due : #_AMOUNT_AFTER_DISCOUNT_#

***********************************
	 * 
	 * 
	 * 
	 * 
	 * @param txn
	 * @param lineList
	 */
	
	
	
	public void mappingTheData(Transaction txn,List<LineItem> lineList){
		
		String textFile = this.getFile("bill_Text.txt");
		String lineItemText = this.getFile("lineItem.txt");
		String numberOfLines = this.getFile("lineNumber.txt");
		String discountTxt = this.getFile("discount.txt");
		

		
		textFile = textFile.replace("#_BILL_NO#", ""+txn.getAutoGeneratedId());
		
		textFile = textFile.replace("#_CUST_ID#", ""+txn.getMobileNumber());
		
		textFile = textFile.replace("#_SUB_TOTAL_#", ""+txn.getSubTotal());
		
		int discount = -1;
		int lineNumber = 10;		
		try {
			discount = Integer.parseInt(txn.getDiscountedAmount().trim());
			//lineNumber = Integer.parseInt(numberOfLines);
		} catch (NumberFormatException e) {
			System.out.println("DISCOUNT ERROR ");
		}
		
		discountTxt = discountTxt.replace("#_DISCOUNT_PERCENT_#", ""+txn.getDiscountPercentage());
		
		discountTxt = discountTxt.replace("#_DISCOUNT_AMOUNT_#", ""+txn.getDiscountedAmount());

		if(discount > 0){
			
		}else if(discount != -1){
			discountTxt = "";
		}
		
		textFile = textFile.replace("#_DISCOUNT_TXT_#", discountTxt);
		
		textFile = textFile.replace("#_AMOUNT_AFTER_DISCOUNT_#", ""+txn.getTotalAfterDiscount());
		
		StringBuffer lineSb = new StringBuffer();
		
		for(LineItem lineItem:lineList){
			String tempItem = new String(lineItemText);
			tempItem = tempItem.replace("#_ITEM_CODE_#", String.format("%2s", lineItem.getItemNumber()));
			tempItem = tempItem.replace("#_ITEM_DESC_#", String.format("%18s", lineItem.getItemDesc()));
			tempItem = tempItem.replace("#_PRICE_#", String.format("%4s", lineItem.getPrice()));
			tempItem = tempItem.replace("#_QUANTITY_#", String.format("%4s", lineItem.getQuantity()));
			tempItem = tempItem.replace("#_FINALAMOUNT_#", String.format("%6s", lineItem.getLineTotal()));
			
//			int parseInt =-1;
//			
//			try{
//				 parseInt = Integer.parseInt(lineItem.getQuantity().trim());	
//				 System.out.println("---"+ parseInt);
//			}catch(Exception e){
//				System.out.println("Item Error");
//			}
//			
//			if(parseInt != -1 && parseInt > 1){
//				String quantityTxt = this.getFile("quantity.txt");
//				quantityTxt = quantityTxt.replace("#_PRICE_#", lineItem.getPrice());
//				quantityTxt = quantityTxt.replace("#_QUANTITY_#", lineItem.getQuantity());
//				quantityTxt = quantityTxt.replace("#_FINALAMOUNT_#", lineItem.getLineTotal());
//				tempItem +=quantityTxt;
//			}
			
			lineSb.append(tempItem);
		 }
		
		textFile = textFile.replace("#_LINE_ITEM_#", lineSb);
		
		System.out.println(textFile);
		PrintReceipt printReceipt = new PrintReceipt( textFile, lineNumber );
	}
	
	
	  private String getFile(String fileName) {

			StringBuilder result = new StringBuilder("");

			//Get file from resources folder
			ClassLoader classLoader = getClass().getClassLoader();
			File file = new File(classLoader.getResource(fileName).getFile());
			
			try{
				Scanner scanner = new Scanner(file);
				while (scanner.hasNextLine()) {
					String line = scanner.nextLine();
					result.append(line).append("\n");
				}

				scanner.close();

			} catch (IOException e) {
				e.printStackTrace();
			}
				
			return result.toString();

		  }
}
