package com.mkyong.web.model;

public class Transaction {
	private String transactionNumber;
	private String discountPercentage;
	private String discountedAmount;
	private String subTotal;
	private String mobileNumber;
	private String totalAfterDiscount;
	private int autoGeneratedId;
	
	
	public String getTotalAfterDiscount() {
		return totalAfterDiscount;
	}
	public void setTotalAfterDiscount(String totalAfterDiscount) {
		this.totalAfterDiscount = totalAfterDiscount;
	}
	public String getTransactionNumber() {
		return transactionNumber;
	}
	public void setTransactionNumber(String transactionNumber) {
		this.transactionNumber = transactionNumber;
	}
	public String getDiscountPercentage() {
		return discountPercentage;
	}
	public void setDiscountPercentage(String discountPercentage) {
		this.discountPercentage = discountPercentage;
	}
	public String getDiscountedAmount() {
		return discountedAmount;
	}
	public void setDiscountedAmount(String discountedAmount) {
		this.discountedAmount = discountedAmount;
	}
	public String getSubTotal() {
		return subTotal;
	}
	public int getAutoGeneratedId() {
		return autoGeneratedId;
	}
	public void setAutoGeneratedId(int autoGeneratedId) {
		this.autoGeneratedId = autoGeneratedId;
	}
	public void setSubTotal(String subTotal) {
		this.subTotal = subTotal;
	}
	public String getMobileNumber() {
		return mobileNumber;
	}
	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}
	
}
