<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<link href="<c:url value="/resources/css/jquery.dataTables.min.css"/>" rel="stylesheet">
<link href="<c:url value="/resources/css/dataTables.bootstrap4.min.css"/>" rel="stylesheet">
<script src="<c:url value="/resources/js/jquery-1.11.2.min.js"/>"></script>
<script src="<c:url value="/resources/js/jquery.dataTables.min.js"/>"></script>
<script src="<c:url value="/resources/js/dataTables.foundation.min.js"/>"></script>

<%@page session="true"%>


	<c:url value="/logout" var="logoutUrl" />
	<form action="${logoutUrl}" method="post" id="logoutForm">
		<input type="hidden" name="${_csrf.parameterName}"
			value="${_csrf.token}" />
	</form>
	<script>
		function formSubmit() {
			document.getElementById("logoutForm").submit();
		}
		
		$(document).ready(function() {
		    $('#example').DataTable();
		} );
	</script>

	<c:if test="${pageContext.request.userPrincipal.name != null}">
		<h2>
			Welcome : ${pageContext.request.userPrincipal.name} | <a
				href="javascript:formSubmit()">Logout</a>
		</h2>
		<table id="example" class="display compact " cellspacing="0" width="100%">
			<thead>
				<tr>
					<td>ID </td>
					<td>Mobile </td>
					<td>Net Total </td>
					<td>Dis % </td>
					<td>Dis Amount </td>
					<td>Bill Amount</td>
					<td>Date</td>
				</tr>
			</thead>

		<tbody>
		<c:forEach var="txn" items="${results}">
			<tr>
					<td>${txn.autoGeneratedId}</td>
					<td>${txn.mobileNumber} </td>
					<td>${txn.subTotal}</td>
					<td>${txn.discountPercentage} </td>
					<td>${txn.discountedAmount}</td>
					<td>${txn.totalAfterDiscount}</td>
					<td>${txn.creationDate}</td>
			</tr>		
		</c:forEach>
		</tbody>
				</table>

		${message}
	</c:if>

<c:if test="${pageContext.request.userPrincipal.name == null}">

	Click here : <a href="/login">Login Page</a>

</c:if>

</body>
</html>

